SET IDENTITY_INSERT [dbo].[Hizmetler] ON
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (1, N'Saç Kesimi', CAST(250.00 AS Decimal(18, 2)), '30 dakika')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (2, N'Fön ve Şekillendirme', CAST(150.00 AS Decimal(18, 2)), '45 dakika')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (3, N'Saç Boyama', CAST(800.00 AS Decimal(18, 2)), '2 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (6, N'Ombre, Sombre, Balyaj', CAST(1500.00 AS Decimal(18, 2)), '2 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (7, N'Keratin Bakımı', CAST(1200.00 AS Decimal(18, 2)), '2 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (8, N'Saç Kaynak', CAST(3000.00 AS Decimal(18, 2)), '3 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (9, N'Düğün ve Özel Gün Saç Tasarımları', CAST(2500.00 AS Decimal(18, 2)), '2.5 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (10, N'Cilt Bakımı', CAST(800.00 AS Decimal(18, 2)), '1.5 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (11, N'Kaş Alma', CAST(150.00 AS Decimal(18, 2)), '20 dakika')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (12, N'Kaş Şekillendirme ve Boyama', CAST(400.00 AS Decimal(18, 2)), '45 dakika')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (13, N'Kirpik Lifting', CAST(700.00 AS Decimal(18, 2)), '1 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (14, N'Takma Kirpik Uygulamaları', CAST(600.00 AS Decimal(18, 2)), '1 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (15, N'Bölgesel Ağda'', ''45 dakika', CAST(300.00 AS Decimal(18, 2)), '45 dakika')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (16, N'Tüm Vücut Ağda', CAST(800.00 AS Decimal(18, 2)), '1.5 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (17, N'Bölgesel Epilasyon', CAST(700.00 AS Decimal(18, 2)), '1 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (18, N'Tüm Vücut Epilasyon', CAST(2000.00 AS Decimal(18, 2)), '2 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (19, N'Manikür ve Pedikür', CAST(450.00 AS Decimal(18, 2)), '1 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (20, N'Protez Tırnak', CAST(1500.00 AS Decimal(18, 2)), '2.5 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (21, N'Nail Art ve Oje Uygulamaları', CAST(800.00 AS Decimal(18, 2)), '1 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (22, N'Profesyonel Makyaj', CAST(1500.00 AS Decimal(18, 2)), '1.5 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (23, N'Günlük Makyaj', CAST(400.00 AS Decimal(18, 2)), '45 dakika')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (24, N'Gelin Paketi (Saç, Makyaj)', CAST(7000.00 AS Decimal(18, 2)), '3 saat')
INSERT INTO [dbo].[Hizmetler] ([HizmetId], [HizmetAdi], [Ucret], [Sure]) VALUES (25, N'Saç ve Cilt Analizi', CAST(200.00 AS Decimal(18, 2)), '45 dakika')

SET IDENTITY_INSERT [dbo].[Hizmetler] OFF
